server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/edunexus
      auto-index-creation: true
  security:
    jwt:
      secret: your-secret-key-here
      expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.edunexus: DEBUG 